//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlogger.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.StatusUpdates = new ObservableCollection<StatusUpdate>();
            this.Authors = new ObservableCollection<Author>();
            this.Genres = new ObservableCollection<Genre>();
        }
    
        public int MaterialID { get; set; }
        public int HobbyID { get; set; }
        public string Title { get; set; }
        public int MaterialFormatID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SubscriptionID { get; set; }
        public Nullable<int> TimeSpent { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public string Info { get; set; }
    
        public virtual Hobby Hobby { get; set; }
        public virtual MaterialFormat MaterialFormat { get; set; }
        public virtual Subscription Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<StatusUpdate> StatusUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Author> Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Genre> Genres { get; set; }
    }
}
