//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlogger.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MaterialsFullReport
    {
        public string Title { get; set; }
        public string HobbyName { get; set; }
        public string FormatType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string AuthorsList { get; set; }
        public string GenresList { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateStatus { get; set; }
        public string SubscriptionName { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public string TotalTime { get; set; }
    }
}
