//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlogger.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class StatusUpdate
    {
        public int UpdateID { get; set; }
        public int MaterialID { get; set; }
        public System.DateTime DateModified { get; set; }
        public int StatusID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Status Status { get; set; }
    }
}
