//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlogger
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BackloggerEntities : DbContext
    {
        public BackloggerEntities()
            : base("name=BackloggerEntities")
        {
            Database.SetInitializer<BackloggerEntities>(new CreateDatabaseIfNotExists<BackloggerEntities>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Hobby> Hobbies { get; set; }
        public virtual DbSet<MaterialFormat> MaterialFormats { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<StatusUpdate> StatusUpdates { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
    }
}
