//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlogger
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Game
    {
        public int MaterialID { get; set; }
        public string Title { get; set; }
        public int MaterialFormatID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SubscriptionID { get; set; }
        public Nullable<int> TimeSpent { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public string Info { get; set; }
    }
}
