//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlogger
{
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MoviesSubscription
    {
        [Key]
        public int SubscriptionID { get; set; }
        public string SubscriptionName { get; set; }
        public decimal Price { get; set; }
        public bool IsActive { get; set; }
    }
}
